image: azabost/android-sdk-28:latest

stages:
  - build
  - quality
  - package

before_script:
  - export ANDROID_HOME="/home/gitlab-runner/android-sdk"
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - export ANDROID_APK_PATH=$PWD/app/build/outputs/apk

#### BUILD ####

.build_template: &build_template_def
  tags:
    - docker
  stage: build
  artifacts:
    expire_in: 2 weeks
    paths:
        - app/build/outputs/
        - .android/

build_onprogress:
    <<: *build_template_def
    stage: build
    only:
      - schedules
      - web
    script:
      - ./gradlew assembleStagingDebug

build_staging:
    <<: *build_template_def
    stage: build
    only:
      - develop
#      - schedules
      - web
    script:
      - ./gradlew assembleStagingDebug


build_release:
    <<: *build_template_def
    stage: build
    only:
      - master
#      - schedules
      - web
    script:
      - ./gradlew assembleProductionRelease
      
     


#### QUALITY ####

quality_check:
    tags:
        - docker
    stage: quality
    only:
        - schedules
        - master
        - develop

    script:
        - ./gradlew ktlint
    
    artifacts:
        name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
        when: on_failure
        expire_in: 4 days
        paths:
            - app/build/reports/
            
#### PACKAGE ####

.package_template: &package_template_def
    tags:
        - docker
    before_script:
        - mkdir -p deliverables
        - touch ./deliverables/info.txt
        - echo "Build date $(date)" >> ./deliverables/info.txt
        - echo "Git branch ${CI_COMMIT_REF_NAME}" >> ./deliverables/info.txt
        - echo "Git commit ${CI_COMMIT_SHA}" >> ./deliverables/info.txt
        - echo "Gitlab pipeline ${CI_PIPELINE_ID}" >> ./deliverables/info.txt
        - export ANDROID_APK_PATH=$PWD/app/build/outputs/apk

package_onprogress:
    <<: *package_template_def
    stage: package
    environment: Development
    only:
      - schedules
      - web
    script:
        - mv $ANDROID_APK_PATH/staging/debug/app-staging-debug*.apk $ANDROID_APK_PATH/staging/debug/app-onprogress-${CI_COMMIT_SHA}.apk
        - curl -F file=@$ANDROID_APK_PATH/staging/debug/app-onprogress-${CI_COMMIT_SHA}.apk -F channels=$SLACK_CHANNEL_ANDROID -F token=$SLACK_TOKEN https://slack.com/api/files.upload

package_staging:
    <<: *package_template_def
    stage: package
    environment: Development
    only:
        - develop
    script:
        - mv $ANDROID_APK_PATH/staging/debug/app-staging-debug*.apk $ANDROID_APK_PATH/staging/debug/app-staging-${CI_COMMIT_SHA}.apk
        - curl -F file=@$ANDROID_APK_PATH/staging/debug/app-staging-${CI_COMMIT_SHA}.apk -F channels=$SLACK_CHANNEL_ANDROID -F token=$SLACK_TOKEN https://slack.com/api/files.upload
        
        
package_release:
    <<: *package_template_def
    stage: package
    environment: Release
    only:
        - master
    script:
        - mv $ANDROID_APK_PATH/production/release/app-production-release*.apk $ANDROID_APK_PATH/production/release/app-production-${CI_COMMIT_SHA}.apk
        - curl -F file=@$ANDROID_APK_PATH/production/release/app-production-${CI_COMMIT_SHA}.apk -F channels=$SLACK_CHANNEL_ANDROID -F token=$SLACK_TOKEN https://slack.com/api/files.upload