image: azabost/android-sdk-28:latest

stages:
  - build

before_script:
  - export ANDROID_HOME="/home/gitlab-runner/android-sdk"
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - export ANDROID_APK_PATH=$PWD/app/build/outputs/apk

# .build_template: &build_template_def
#   stage: build
#   artifacts:
#     expire_in: 2 weeks
#     paths:
#       - app/build/outputs/
#       - .android/

build_debug:
    # <<: *build_template_def
    stage: build
    only:
#        - develop
      - schedules
      - web
    script:
      - ./gradlew assembleDebug
      - "curl --request POST --header \"Content-Type: multipart/form-data;\" --form \"token=$SLACK_TOKEN\" --form \"channels=$SLACK_CHANNELS\" --form \"content=$SLACK_CONTENT\" --form \"file=@$ANDROID_APK_PATH/debug/app-debug*.apk\" --form \"title=TestCI\" https://slack.com/api/files.upload"
    artifacts:
      paths:
        - app/build/outputs/

# build_staging:
#     <<: *build_template_def
#     only:
# #        - develop
#       - schedules
#       - web
#     script:
#       - ./gradlew assembleStaging
#       - "curl --request POST --header \"Content-Type: multipart/form-data;\" --form \"token=$SLACK_TOKEN\" --form \"channels=$SLACK_CHANNELS\" --form \"content=$SLACK_CONTENT\" --form \"file=@$CI_PROJECT_DIR/$APK_PATH\" --form \"title=$SLACK_TITLE : $CI_COMMIT_REF_SLUG || $CI_COMMIT_SHA\" https://slack.com/api/files.upload"

# build_production:
#     stage: build
#     artifacts:
#       paths:
#           - app/build/outputs/
#           - .android/
#     only:
#         - master
#     script:
#       - ./gradlew assembleProduction
#       - "curl --request POST --header \"Content-Type: multipart/form-data;\" --form \"token=$SLACK_TOKEN\" --form \"channels=$SLACK_CHANNELS\" --form \"content=$SLACK_CONTENT_PRODUCTION\" --form \"file=@$CI_PROJECT_DIR/$APK_PATH_PRODUCTION\" --form \"title=$SLACK_TITLE_PRODUCTION : $CI_COMMIT_REF_SLUG || $CI_COMMIT_SHA\" https://slack.com/api/files.upload"