image: azabost/android-sdk-28:latest

stages:
  - build
  - quality
  - package

before_script:
  - export ANDROID_HOME="/home/gitlab-runner/android-sdk"
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - export ANDROID_APK_PATH=$PWD/app/build/outputs/apk

#### BUILD ####

.build_template: &build_template_def
  stage: build
  artifacts:
    expire_in: 2 weeks
    paths:
        - app/build/outputs/
        - .android/

build_onprogress:
    <<: *build_template_def
    stage: build
    only:
      - schedules
      - web
    except:
      - develop
      - master
    script:
      - echo "org.gradle.jvmargs=-Xmx1536m" >> gradle.properties
      - echo "SYMBOLIC_REDIRECT_URI=$SYMBOLIC_REDIRECT_URI_STAG" >> gradle.properties
      - echo "PANTAU_BASE_URL=$PANTAU_BASE_URL_STAG" >> gradle.properties
      - echo "PANTAU_BASE_URL_NO_SCHEME=$PANTAU_BASE_URL_NO_SCHEME_STAG" >> gradle.properties
      - echo "PANTAU_OAUTH_URL=$PANTAU_OAUTH_URL_STAG" >> gradle.properties
      - echo "WORD_STADIUM_BASE_URL=$WORD_STADIUM_BASE_URL_STAG" >> gradle.properties
      - echo "SYMBOLIC_URL=$SYMBOLIC_URL_STAG" >> gradle.properties
      - echo "SYMBOLIC_URL_NO_SCHEME=$SYMBOLIC_URL_NO_SCHEME_STAG" >> gradle.properties
      - echo "SYMBOLIC_CLIENT_ID=$SYMBOLIC_CLIENT_ID_STAG" >> gradle.properties
      - echo "SYMBOLIC_CLIENT_SECRET=$SYMBOLIC_CLIENT_SECRET_STAG" >> gradle.properties
      - echo "FACEBOOK_APP_ID=$FACEBOOK_APP_ID_STAG" >> gradle.properties
      - echo "FACEBOOK_LOGIN_PROTOCOL_SCHEME=$FACEBOOK_LOGIN_PROTOCOL_SCHEME_STAG" >> gradle.properties
      - echo "TWITTER_API_KEY=$TWITTER_API_KEY_STAG" >> gradle.properties
      - echo "TWITTER_SECRET=$TWITTER_SECRET_STAG" >> gradle.properties
      - echo "PANTAU_CLIENT_ID=$PANTAU_CLIENT_ID_STAG" >> gradle.properties
      - echo "PANTAU_CLIENT_SECRET=$PANTAU_CLIENT_SECRET_STAG" >> gradle.properties
      - echo "android.useAndroidX=true" >> gradle.properties
      - echo "android.enableJetifier=true" >> gradle.properties
      - ./gradlew assembleStagingDebug

build_staging:
    <<: *build_template_def
    stage: build
    only:
      - develop
#      - schedules
      - web
    except:
      - onprogress
      - master
    script:
      - echo "org.gradle.jvmargs=-Xmx1536m" >> gradle.properties
      - echo "SYMBOLIC_REDIRECT_URI=$SYMBOLIC_REDIRECT_URI_STAG" >> gradle.properties
      - echo "PANTAU_BASE_URL=$PANTAU_BASE_URL_STAG" >> gradle.properties
      - echo "PANTAU_BASE_URL_NO_SCHEME=$PANTAU_BASE_URL_NO_SCHEME_STAG" >> gradle.properties
      - echo "PANTAU_OAUTH_URL=$PANTAU_OAUTH_URL_STAG" >> gradle.properties
      - echo "WORD_STADIUM_BASE_URL=$WORD_STADIUM_BASE_URL_STAG" >> gradle.properties
      - echo "SYMBOLIC_URL=$SYMBOLIC_URL_STAG" >> gradle.properties
      - echo "SYMBOLIC_URL_NO_SCHEME=$SYMBOLIC_URL_NO_SCHEME_STAG" >> gradle.properties
      - echo "SYMBOLIC_CLIENT_ID=$SYMBOLIC_CLIENT_ID_STAG" >> gradle.properties
      - echo "SYMBOLIC_CLIENT_SECRET=$SYMBOLIC_CLIENT_SECRET_STAG" >> gradle.properties
      - echo "FACEBOOK_APP_ID=$FACEBOOK_APP_ID_STAG" >> gradle.properties
      - echo "FACEBOOK_LOGIN_PROTOCOL_SCHEME=$FACEBOOK_LOGIN_PROTOCOL_SCHEME_STAG" >> gradle.properties
      - echo "TWITTER_API_KEY=$TWITTER_API_KEY_STAG" >> gradle.properties
      - echo "TWITTER_SECRET=$TWITTER_SECRET_STAG" >> gradle.properties
      - echo "PANTAU_CLIENT_ID=$PANTAU_CLIENT_ID_STAG" >> gradle.properties
      - echo "PANTAU_CLIENT_SECRET=$PANTAU_CLIENT_SECRET_STAG" >> gradle.properties
      - echo "android.useAndroidX=true" >> gradle.properties
      - echo "android.enableJetifier=true" >> gradle.properties
      - ./gradlew assembleStagingDebug


build_release:
    <<: *build_template_def
    stage: build
    only:
      - master
#      - schedules
      - web
    except:
      - onprogress
      - develop
    script:
      - echo "org.gradle.jvmargs=-Xmx1536m" >> gradle.properties
      - echo "SYMBOLIC_REDIRECT_URI=$SYMBOLIC_REDIRECT_URI_PROD" >> gradle.properties
      - echo "PANTAU_BASE_URL=$PANTAU_BASE_URL_PROD" >> gradle.properties
      - echo "PANTAU_BASE_URL_NO_SCHEME=$PANTAU_BASE_URL_NO_SCHEME_PROD" >> gradle.properties
      - echo "PANTAU_OAUTH_URL=$PANTAU_OAUTH_URL_PROD" >> gradle.properties
      - echo "WORD_STADIUM_BASE_URL=$WORD_STADIUM_BASE_URL_PROD" >> gradle.properties
      - echo "SYMBOLIC_URL=$SYMBOLIC_URL_PROD" >> gradle.properties
      - echo "SYMBOLIC_URL_NO_SCHEME=$SYMBOLIC_URL_NO_SCHEME_PROD" >> gradle.properties
      - echo "SYMBOLIC_CLIENT_ID=$SYMBOLIC_CLIENT_ID_PROD" >> gradle.properties
      - echo "SYMBOLIC_CLIENT_SECRET=$SYMBOLIC_CLIENT_SECRET_PROD" >> gradle.properties
      - echo "FACEBOOK_APP_ID=$FACEBOOK_APP_ID_PROD" >> gradle.properties
      - echo "FACEBOOK_LOGIN_PROTOCOL_SCHEME=$FACEBOOK_LOGIN_PROTOCOL_SCHEME_PROD" >> gradle.properties
      - echo "TWITTER_API_KEY=$TWITTER_API_KEY_PROD" >> gradle.properties
      - echo "TWITTER_SECRET=$TWITTER_SECRET_PROD" >> gradle.properties
      - echo "PANTAU_CLIENT_ID=$PANTAU_CLIENT_ID_PROD" >> gradle.properties
      - echo "PANTAU_CLIENT_SECRET=$PANTAU_CLIENT_SECRET_PROD" >> gradle.properties
      - echo "android.useAndroidX=true" >> gradle.properties
      - echo "android.enableJetifier=true" >> gradle.properties
      - ./gradlew assembleProductionRelease
      
     


#### QUALITY ####

quality_check:
    stage: quality
    only:
        - master
        - develop

    script:
        - echo "org.gradle.jvmargs=-Xmx1536m" >> gradle.properties
        - echo "SYMBOLIC_REDIRECT_URI=$SYMBOLIC_REDIRECT_URI_PROD" >> gradle.properties
        - echo "PANTAU_BASE_URL=$PANTAU_BASE_URL_PROD" >> gradle.properties
        - echo "PANTAU_BASE_URL_NO_SCHEME=$PANTAU_BASE_URL_NO_SCHEME_PROD" >> gradle.properties
        - echo "PANTAU_OAUTH_URL=$PANTAU_OAUTH_URL_PROD" >> gradle.properties
        - echo "WORD_STADIUM_BASE_URL=$WORD_STADIUM_BASE_URL_PROD" >> gradle.properties
        - echo "SYMBOLIC_URL=$SYMBOLIC_URL_PROD" >> gradle.properties
        - echo "SYMBOLIC_URL_NO_SCHEME=$SYMBOLIC_URL_NO_SCHEME_PROD" >> gradle.properties
        - echo "SYMBOLIC_CLIENT_ID=$SYMBOLIC_CLIENT_ID_PROD" >> gradle.properties
        - echo "SYMBOLIC_CLIENT_SECRET=$SYMBOLIC_CLIENT_SECRET_PROD" >> gradle.properties
        - echo "FACEBOOK_APP_ID=$FACEBOOK_APP_ID_PROD" >> gradle.properties
        - echo "FACEBOOK_LOGIN_PROTOCOL_SCHEME=$FACEBOOK_LOGIN_PROTOCOL_SCHEME_PROD" >> gradle.properties
        - echo "TWITTER_API_KEY=$TWITTER_API_KEY_PROD" >> gradle.properties
        - echo "TWITTER_SECRET=$TWITTER_SECRET_PROD" >> gradle.properties
        - echo "PANTAU_CLIENT_ID=$PANTAU_CLIENT_ID_PROD" >> gradle.properties
        - echo "PANTAU_CLIENT_SECRET=$PANTAU_CLIENT_SECRET_PROD" >> gradle.properties
        - echo "android.useAndroidX=true" >> gradle.properties
        - echo "android.enableJetifier=true" >> gradle.properties
        - ./gradlew ktlint
    
    artifacts:
        name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
        when: on_failure
        expire_in: 4 days
        paths:
            - app/build/reports/
            
#### PACKAGE ####

.package_template: &package_template_def
    before_script:
        - mkdir -p deliverables
        - touch ./deliverables/info.txt
        - echo "Build date $(date)" >> ./deliverables/info.txt
        - echo "Git branch ${CI_COMMIT_REF_NAME}" >> ./deliverables/info.txt
        - echo "Git commit ${CI_COMMIT_SHA}" >> ./deliverables/info.txt
        - echo "Gitlab pipeline ${CI_PIPELINE_ID}" >> ./deliverables/info.txt
        - export ANDROID_APK_PATH=$PWD/app/build/outputs/apk

package_onprogress:
    <<: *package_template_def
    stage: package
    environment: Development
    only:
      - schedules
      - web
    script:
        - mv $ANDROID_APK_PATH/staging/debug/app-staging-debug*.apk $ANDROID_APK_PATH/staging/debug/app-onprogress-${CI_COMMIT_SHA}.apk
        - curl -F file=@$ANDROID_APK_PATH/staging/debug/app-onprogress-${CI_COMMIT_SHA}.apk -F channels=$SLACK_CHANNEL_ANDROID -F token=$SLACK_TOKEN https://slack.com/api/files.upload
        - curl -F file=@$ANDROID_APK_PATH/staging/debug/app-onprogress-${CI_COMMIT_SHA}.apk -F channels=$SLACK_CHANNEL_LAPORAN_BUG -F token=$SLACK_TOKEN https://slack.com/api/files.upload

package_staging:
    <<: *package_template_def
    stage: package
    environment: Development
    only:
        - develop
    script:
        - mv $ANDROID_APK_PATH/staging/debug/app-staging-debug*.apk $ANDROID_APK_PATH/staging/debug/app-staging-${CI_COMMIT_SHA}.apk
        - curl -F file=@$ANDROID_APK_PATH/staging/debug/app-staging-${CI_COMMIT_SHA}.apk -F channels=$SLACK_CHANNEL_ANDROID -F token=$SLACK_TOKEN https://slack.com/api/files.upload
        - curl -F file=@$ANDROID_APK_PATH/staging/debug/app-staging-${CI_COMMIT_SHA}.apk -F channels=$SLACK_CHANNEL_LAPORAN_BUG -F token=$SLACK_TOKEN https://slack.com/api/files.upload
        
        
package_release:
    <<: *package_template_def
    stage: package
    environment: Release
    only:
        - master
    script:
        - mv $ANDROID_APK_PATH/production/release/app-production-release*.apk $ANDROID_APK_PATH/production/release/app-production-${CI_COMMIT_SHA}.apk
        - curl -F file=@$ANDROID_APK_PATH/production/release/app-production-${CI_COMMIT_SHA}.apk -F channels=$SLACK_CHANNEL_ANDROID -F token=$SLACK_TOKEN https://slack.com/api/files.upload
        - curl -F file=@$ANDROID_APK_PATH/production/release/app-production-${CI_COMMIT_SHA}.apk -F channels=$SLACK_CHANNEL_LAPORAN_BUG -F token=$SLACK_TOKEN https://slack.com/api/files.upload